sudo: required
dist: trusty
group: edge

branches:
  only:
  - master

language: php

php:
  - 7.0

git:
  depth: 3

cache:
  apt: true
  pip: true
  directories:
    - $HOME/.composer/cache

before_install:
  - bash $TRAVIS_BUILD_DIR/before-install.sh

install: true
script: true