sudo: required
dist: trusty
group: edge

branches:
  only:
  - master

language: php

php:
  - 7.0

git:
  depth: 3

env:
  global:
    - COMPOSER_BIN_DIR=$HOME/bin

cache:
  apt: true
  pip: true
  directories:
    - $HOME/.composer/cache

before_install:
  - bash $TRAVIS_BUILD_DIR/before-install.sh

install: true
script: true

jobs:
  include:
    - stage: "Code standard for test.php"
      script: bash $TRAVIS_BUILD_DIR/scan-code.sh test.php
    - stage: "Code standard for test.php"
      script: bash $TRAVIS_BUILD_DIR/scan-code.sh test.php